### ISSUE TITLE
When I just include library to gradle I get TintManager error

### ISSUE THREAD

**Issue by egslava** [FuckBoilerplate/RxPaparazzo#4]
```
05-05 13:49:21.336 14924-14924/com.example.someapp E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.example.someapp, PID: 14924
   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;
       at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1185)
       at android.support.design.widget.TabLayout.createTabView(TabLayout.java:656)
       at android.support.design.widget.TabLayout.addTabView(TabLayout.java:695)
       at android.support.design.widget.TabLayout.addTab(TabLayout.java:386)
       at android.support.design.widget.TabLayout.addTab(TabLayout.java:361)
       at android.support.design.widget.TabLayout.setTabsFromPagerAdapter(TabLayout.java:645)
       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:616)
       at com.example.someapp.ui.navigation.trade.TradeFragment.onViewCreated(TradeFragment.kt:201)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
       at com.trello.navi.component.support.NaviAppCompatActivity.onStart(NaviAppCompatActivity.java:41)
       at com.example.someapp.api.messaging.NetActivity.onStart(NetActivity.java:70)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.TintManager" on path: DexPathList[[zip file "/data/app/com.example.someapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.someapp-2/lib/arm, /data/app/com.example.someapp-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1185) 
       at android.support.design.widget.TabLayout.createTabView(TabLayout.java:656) 
       at android.support.design.widget.TabLayout.addTabView(TabLayout.java:695) 
       at android.support.design.widget.TabLayout.addTab(TabLayout.java:386) 
       at android.support.design.widget.TabLayout.addTab(TabLayout.java:361) 
       at android.support.design.widget.TabLayout.setTabsFromPagerAdapter(TabLayout.java:645) 
       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:616) 
       at com.example.someapp.ui.navigation.trade.TradeFragment.onViewCreated(TradeFragment.kt:201) 
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086) 
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
       at com.trello.navi.component.support.NaviAppCompatActivity.onStart(NaviAppCompatActivity.java:41) 
       at com.example.someapp.api.messaging.NetActivity.onStart(NetActivity.java:70) 
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
       at android.app.Activity.performStart(Activity.java:6268) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:148) 
       at android.app.ActivityThread.main(ActivityThread.java:5417) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   	Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.TintManager
       at java.lang.Class.classForName(Native Method)
       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
       		... 29 more
    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by egslava** [comment]
Updated def support library version to '23.3.0' and now everything is okay :-)

**Comment by miguelbcr** [comment]
Hi @egslava,
ok, I'm glad to hear that :).
I was just writing to you to update support library version  as a first attempt to solve it.

**Comment by caishengyan** [comment]
solved the problem
